import type { Locale } from "./types"

export const CONNECTION_STORAGE_KEY = "pixel-bench-connection-v1"

export const MODEL_OPTIONS = [
  {
    value: "gpt-image-2",
    label: "gpt-image-2",
    description: {
      zh: "OpenAI 兼容图像生成与编辑",
      en: "OpenAI-compatible image generation and edits",
    },
  },
]

export const SIZE_OPTIONS = [
  { value: "1024x1024", label: { zh: "方图", en: "Square" }, detail: "1:1" },
  { value: "1024x1536", label: { zh: "竖图", en: "Portrait" }, detail: "2:3" },
  { value: "1536x1024", label: { zh: "横图", en: "Landscape" }, detail: "3:2" },
  { value: "auto", label: { zh: "自动", en: "Auto" }, detail: "AUTO" },
]

export const QUALITY_OPTIONS = [
  { value: "auto", label: { zh: "自动", en: "Auto" } },
  { value: "low", label: { zh: "草稿", en: "Low" } },
  { value: "medium", label: { zh: "标准", en: "Medium" } },
  { value: "high", label: { zh: "精细", en: "High" } },
]

export const FORMAT_OPTIONS = [
  { value: "png", label: "PNG" },
  { value: "webp", label: "WEBP" },
  { value: "jpeg", label: "JPEG" },
]

export const COPY = {
  zh: {
    appName: "像素工台",
    appMeta: "OpenAI 兼容图像生成与编辑控制台",
    statusPrivate: "浏览器会话优先",
    language: "中文",
    languageAlt: "English",
    theme: "主题",
    themeLight: "亮色",
    themeDark: "暗色",
    themeSystem: "跟随系统",
    settings: "设置",
    settingsOpen: "展开设置",
    settingsClose: "收起设置",
    connection: "连接设置",
    connectionHint: "接口地址、密钥和模型集中管理",
    baseUrl: "接口地址",
    baseUrlHint: "例如：https://api.openai.com",
    apiKey: "API 密钥",
    secretUnset: "未填写",
    secretSaved: "已填写",
    configured: "已配置",
    notConfigured: "待配置",
    model: "模型",
    remember: "记住连接信息",
    rememberHint: "开启后写入此浏览器的 localStorage，只适合个人设备。",
    remembered: "已在本机记住",
    notRemembered: "不会跨会话保存",
    compose: "创作表单",
    composeHint: "只保留画面描述、参考图和输出规格",
    prompt: "画面描述",
    promptHint: "写清主体、材质、构图、光线与限制条件",
    promptPlaceholder: "描述你要生成或编辑的图像…",
    reference: "参考图",
    referenceHint: "上传后使用图片编辑兼容接口",
    referenceDrop: "选择一张参考图",
    referenceDropHint: "PNG、JPG、WEBP 等图片文件；不会在服务端落盘。",
    referenceActive: "参考图已启用",
    referenceRemove: "移除参考图",
    output: "输出规格",
    outputHint: "尺寸、质量、格式与背景",
    size: "尺寸",
    quality: "质量",
    format: "格式",
    imageCount: "数量",
    transparent: "透明背景",
    transparentHint: "适合 PNG/贴图素材；由兼容接口决定是否支持。",
    generate: "生成图像",
    edit: "编辑参考图",
    generating: "正在处理…",
    preview: "预览画布",
    previewHint: "结果只保留在当前浏览器会话中",
    emptyTitle: "等待第一张图像",
    emptyBody: "完成设置与创作参数后，结果会出现在这张光栅画布上。",
    loadingTitle: "正在请求图像接口",
    loadingGenerate: "当前模式：从提示词生成新图像。",
    loadingEdit: "当前模式：基于参考图进行图片编辑。",
    resultMeta: "图像结果",
    revisedPrompt: "修订提示词",
    generatedOutput: "生成输出",
    download: "下载",
    requestSummary: "请求摘要",
    privacyMemory: "连接信息已按你的开关保存在本浏览器。",
    privacySession: "连接信息只保留在当前页面状态中。",
    modeGenerate: "生成模式",
    modeEdit: "参考图编辑",
    validateBaseUrl: "请输入以 http:// 或 https:// 开头的接口地址。",
    validateApiKey: "请输入 API 密钥。",
    validatePrompt: "请输入画面描述。",
    validateCount: "数量必须在 1 到 4 之间。",
    validateReference: "请选择有效的图片文件。",
    requestFailed: "图像生成失败。",
    editFailed: "图片编辑失败。",
    noImage: "接口没有返回图像数据。",
  },
  en: {
    appName: "Pixel Bench",
    appMeta: "OpenAI-compatible image generation and edit console",
    statusPrivate: "Browser-session first",
    language: "English",
    languageAlt: "中文",
    theme: "Theme",
    themeLight: "Light",
    themeDark: "Dark",
    themeSystem: "System",
    settings: "Settings",
    settingsOpen: "Open settings",
    settingsClose: "Close settings",
    connection: "Connection settings",
    connectionHint: "Base URL, key, and model in one place",
    baseUrl: "Base URL",
    baseUrlHint: "Example: https://api.openai.com",
    apiKey: "API key",
    secretUnset: "Not set",
    secretSaved: "Set",
    configured: "Configured",
    notConfigured: "Setup needed",
    model: "Model",
    remember: "Remember connection",
    rememberHint: "Stores values in this browser localStorage. Use only on personal devices.",
    remembered: "Remembered locally",
    notRemembered: "Not saved across sessions",
    compose: "Creation form",
    composeHint: "Prompt, reference image, and output specs only",
    prompt: "Prompt",
    promptHint: "Describe subject, material, composition, light, and constraints",
    promptPlaceholder: "Describe the image you want to generate or edit…",
    reference: "Reference image",
    referenceHint: "Uploaded images use the image edits endpoint",
    referenceDrop: "Choose a reference image",
    referenceDropHint: "PNG, JPG, WEBP, and similar image files. Nothing is stored server-side.",
    referenceActive: "Reference enabled",
    referenceRemove: "Remove reference",
    output: "Output specs",
    outputHint: "Size, quality, format, and background",
    size: "Size",
    quality: "Quality",
    format: "Format",
    imageCount: "Count",
    transparent: "Transparent background",
    transparentHint: "Useful for PNG assets and textures; support depends on the provider.",
    generate: "Generate image",
    edit: "Edit reference",
    generating: "Processing…",
    preview: "Preview canvas",
    previewHint: "Returned images stay in this browser session",
    emptyTitle: "Waiting for the first image",
    emptyBody: "Complete settings and creation controls. Results appear on this raster canvas.",
    loadingTitle: "Requesting image endpoint",
    loadingGenerate: "Current mode: create a new image from the prompt.",
    loadingEdit: "Current mode: edit from the reference image.",
    resultMeta: "Image result",
    revisedPrompt: "Revised prompt",
    generatedOutput: "Generated output",
    download: "Download",
    requestSummary: "Request summary",
    privacyMemory: "Connection info is saved in this browser as requested.",
    privacySession: "Connection info is kept only in the current page state.",
    modeGenerate: "Generation mode",
    modeEdit: "Reference edit",
    validateBaseUrl: "Enter a base URL that starts with http:// or https://.",
    validateApiKey: "Enter an API key.",
    validatePrompt: "Enter a prompt before creating an image.",
    validateCount: "Image count must be between 1 and 4.",
    validateReference: "Choose a valid image file.",
    requestFailed: "Image generation failed.",
    editFailed: "Image edit failed.",
    noImage: "The provider returned no image data.",
  },
} satisfies Record<Locale, Record<string, string>>
